[package]
name = "fantoccini_shiprock"
version = "0.1.0"
authors = ["Clifford T. Matthews <clifford.t.matthews@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.19.3"
serde_json = "1.0.93"
nom = "7.1.3"
digital-duration-nom = { version = "0.4.0", git = "https://github.com/ctm/digital-duration-nom" }
serde = { version = "1.0.152", features = ["derive"] }
structopt = "0.3.26"
async-trait = "0.1.64"
futures = "0.3.26"
anyhow = "1.0.69"

[dependencies.tokio]
version = "1.25.0"
features = ["macros", "time", "rt-multi-thread"]
