[package]
name = "fantoccini_shiprock"
version = "0.1.0"
authors = ["Clifford T. Matthews <clifford.t.matthews@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.14"
serde_json = "1.0.40"
webdriver = "0.41.0" # NOTE: only need this due to needing "internal" error
nom = "6.0"
digital-duration-nom = { version = "0.1.0", git = "https://github.com/ctm/digital-duration-nom" }
serde = { version = "1.0.94", features = ["derive"] }
structopt = "0.3.9"
async-trait = "0.1.10"

[dependencies.tokio]
version = "0.3.3"
features = ["macros", "rt-multi-thread"]
