[package]
name = "fantoccini_shiprock"
version = "0.1.0"
authors = ["Clifford T. Matthews <clifford.t.matthews@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fantoccini = "0.14"
serde_json = "1.0.40"
webdriver = "0.41.0" # NOTE: only need this due to needing "internal" error
nom = "6.0"
digital-duration-nom = { version = "0.1.0", git = "https://github.com/ctm/digital-duration-nom" }
serde = { version = "1.0.94", features = ["derive"] }
structopt = "0.3.9"
async-trait = "0.1.10"
futures = "0.3.7"
anyhow = "1.0"

[dependencies.tokio]
# Can't use tokio 0.3.3 yet because fantoccini itself uses 0.2.22
# version = "0.3.3"
version = "0.2.22"
features = ["macros", "time"]
